apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollout
  namespace: argocd-system
spec:
  project: default
  source:
    repoURL: "https://github.com/miragecentury/instant-search-demo-argocd.git"
    targetRevision: HEAD
    path: "./argo-rollout"
  destination:
    server: https://kubernetes.default.svc
    namespace: "argo-rollouts"
  syncPolicy:
    automated:
      prune: true
  ignoreDifferences:
    - group: apiextentions.k8s.io
      kind: CustomResourceDefinition
      name: analysisruns.argoproj.io
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextentions.k8s.io
      kind: CustomResourceDefinition
      name: analysistemplates.argoproj.io
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextentions.k8s.io
      kind: CustomResourceDefinition
      name: clusteranalysistemplates.argoproj.io
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextentions.k8s.io
      kind: CustomResourceDefinition
      name: experiments.argoproj.io
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextentions.k8s.io
      kind: CustomResourceDefinition
      name: rollouts.argoproj.io
      jsonPointers:
        - /spec/preserveUnknownFields

