apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: instant-search-demo
  namespace: argocd-system
spec:
  project: default
  source:
    repoURL: "https://github.com/miragecentury/instant-search-demo-argocd.git"
    targetRevision: HEAD
    path: "./instant-search-demo"
  destination:
    server: https://kubernetes.default.svc
    namespace: "instant-search-demo"
  syncPolicy:
    automated:
      prune: true
