apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: instant-search-demo
  namespace: instant-search-demo
  labels:
    app: instant-search-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: instant-search-demo
  template:
    metadata:
      namespace: instant-search-demo
      labels:
        app: instant-search-demo
    spec:
      containers:
      - name: instant-search-demo
        image: "ghcr.io/miragecentury/instant-search-demo:v0.0.5"
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: 400Mi
          requests:
            cpu: "0.5"
            memory: 200Mi
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: instant-search-demo-next
  namespace: instant-search-demo
  labels:
    app: instant-search-demo-next
spec:
  replicas: 2
  selector:
    matchLabels:
      app: instant-search-demo-next
  template:
    metadata:
      namespace: instant-search-demo
      labels:
        app: instant-search-demo-next
    spec:
      containers:
      - name: instant-search-demo-next
        image: "ghcr.io/miragecentury/instant-search-demo:v0.0.6"
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: 400Mi
          requests:
            cpu: "0.5"
            memory: 200Mi
